"""
Reflections/memory formatting utilities.
Matches the original TypeScript formatReflections function.
"""

from typing import Optional

from core.types import Reflections


def format_reflections(
    reflections: Reflections,
    only_style: bool = False,
    only_content: bool = False,
) -> str:
    """
    Format reflections for use in prompts.
    
    Args:
        reflections: The reflections object
        only_style: Return only style guidelines
        only_content: Return only content/facts
        
    Returns:
        Formatted string for prompt injection
        
    Raises:
        ValueError: If both only_style and only_content are True
    """
    if only_style and only_content:
        raise ValueError("Cannot specify both only_style and only_content as True.")
    
    # Format style rules
    style_rules = reflections.style_rules or []
    if isinstance(style_rules, str):
        try:
            import json
            style_rules = json.loads(style_rules)
        except (json.JSONDecodeError, TypeError):
            print(f"Warning: Failed to parse style rules: {style_rules}")
            style_rules = []
    
    style_rules_str = "\n- ".join(style_rules) if style_rules else "No style guidelines found."
    
    # Format content/facts
    content_rules = reflections.content or []
    if isinstance(content_rules, str):
        try:
            import json
            content_rules = json.loads(content_rules)
        except (json.JSONDecodeError, TypeError):
            print(f"Warning: Failed to parse content rules: {content_rules}")
            content_rules = []
    
    content_rules_str = "\n- ".join(content_rules) if content_rules else "No memories/facts found."
    
    # Build output strings
    style_string = f"""The following is a list of style guidelines previously generated by you:
<style-guidelines>
- {style_rules_str}
</style-guidelines>"""

    content_string = f"""The following is a list of memories/facts you previously generated about the user:
<user-facts>
- {content_rules_str}
</user-facts>"""

    if only_style:
        return style_string
    if only_content:
        return content_string
    
    return f"{style_string}\n\n{content_string}"


def get_formatted_reflections(
    reflections: Optional[Reflections],
    only_style: bool = False,
    only_content: bool = False,
) -> str:
    """
    Safely format reflections, handling None case.
    
    Args:
        reflections: Optional reflections object
        only_style: Return only style guidelines
        only_content: Return only content/facts
        
    Returns:
        Formatted string or default message
    """
    if not reflections:
        return "No reflections found."
    
    return format_reflections(
        reflections,
        only_style=only_style,
        only_content=only_content,
    )
